ALTER TABLE rooms ADD COLUMN room_type VARCHAR(50) NOT NULL DEFAULT 'STANDARD';
ALTER TABLE rooms ADD COLUMN meal_plan VARCHAR(50) NOT NULL DEFAULT 'ROOM_ONLY';

CREATE TABLE room_amenities (
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    amenity VARCHAR(50) NOT NULL,
    PRIMARY KEY (room_id, amenity)
);
